import { OptRow } from "tui-grid/types/options";

export interface TableDataItem {
  key: number;
  name: string;
  artist: string;
  type: string;
  genre: string;
  release: string;
  price: string;
  download: string;
  listen: string;
}

export const TableData: OptRow[] = [
  {
    key: 0,
    name: 'Beautiful Lies',
    artist: 'Birdy',
    type: 'Deluxe;',
    genre: 'Pop',
    release: '2016-03-26',
    price: '10000',
    download: '1000',
    listen: '10050',
  },
  {
    key: 1,
    name: 'X',
    artist: 'Ed Sheeran',
    type: 'Deluxe;',
    genre: '',
    release: '',
    price: '20000',
    download: '1900',
    listen: '2005',
  },
  {
    key: 2,
    name: 'Moves Like Jagger',
    artist: 'Maroon5',
    type: 'Single;',
    genre: 'Pop,Rock',
    release: '2011-08-08',
    price: '7000',
    download: '11000',
    listen: '3100',
  },
  {
    key: 3,
    name: 'A Head Full Of Dreams',
    artist: 'Coldplay',
    type: 'Deluxe;',
    genre: 'Rock',
    release: '2015-12-04',
    price: '25000',
    download: '2230',
    listen: '4030',
  },
  {
    key: 4,
    name: '21',
    artist: 'Adele',
    type: 'Deluxe;',
    genre: 'Pop,R&B',
    release: '2011-01-21',
    price: '15000',
    download: '1007',
    listen: '12000',
  },
  {
    key: 5,
    name: 'Warm On A Cold Night',
    artist: 'HONNE',
    type: 'EP;',
    genre: 'R&B,Electronic',
    release: '2016-07-22',
    price: '11000',
    download: '1502',
    listen: '5000',
  },
  {
    key: 6,
    name: 'Take Me To The Alley',
    artist: 'Gregory Porter',
    type: 'Deluxe;',
    genre: 'Jazz',
    release: '2016-09-02',
    price: '30000',
    download: '1200',
    listen: '5003',
  },
  {
    key: 7,
    name: 'Make Out',
    artist: 'LANY',
    type: 'EP;',
    genre: 'Electronic',
    release: '2015-12-11',
    price: '12000',
    download: '8005',
    listen: '9000',
  },
  {
    key: 8,
    name: 'Get Lucky',
    artist: 'Daft Punk',
    type: 'Single',
    genre: 'Pop,Funk',
    release: '2013-04-23',
    price: '9000',
    download: '11000',
    listen: '1500',
  },
  {
    key: 9,
    name: 'Valtari',
    artist: 'Sigur Rós',
    type: 'EP;',
    genre: 'Rock',
    release: '2012-05-31',
    price: '10000',
    download: '9000',
    listen: '8010',
  },
  {
    key: 10,
    name: 'Bush',
    artist: 'Snoop Dogg',
    type: 'EP',
    genre: 'Hiphop',
    release: '2015-05-12',
    price: '18000',
    download: '3000',
    listen: '2005',
  },
  {
    key: 11,
    name: 'Chaos And The Calm',
    artist: 'James Bay',
    type: 'EP',
    genre: 'Pop,Rock',
    release: '2015-03-23',
    price: '12000',
    download: '8007',
    listen: '9000',
  },
  {
    key: 12,
    name: '4',
    artist: 'Beyoncé',
    type: 'Deluxe',
    genre: 'Pop',
    release: '2011-07-26',
    price: '12000',
    download: '7000',
    listen: '11002',
  },
  {
    key: 13,
    name: "I Won't Give Up",
    artist: 'Jason Mraz',
    type: 'Single',
    genre: 'Pop',
    release: '2012-01-03',
    price: '7000',
    download: '8000',
    listen: '2000',
  },
  {
    key: 14,
    name: 'Following My Intuition',
    artist: 'Craig David',
    type: 'Deluxe',
    genre: 'R&B,Electronic',
    release: '2016-10-01',
    price: '15000',
    download: '9001',
    listen: '8100',
  },
  {
    key: 15,
    name: 'Blue Skies',
    artist: 'Lenka',
    type: 'Single',
    genre: 'Pop,Rock',
    release: '2015-03-18',
    price: '6000',
    download: '11000',
    listen: '9000',
  },
  {
    key: 16,
    name: 'This Is Acting',
    artist: 'Sia',
    type: 'EP',
    genre: 'Pop',
    release: '2016-10-22',
    price: '20000',
    download: '11400',
    listen: '5800',
  },
  {
    key: 17,
    name: 'Blurryface',
    artist: 'Twenty One Pilots',
    type: 'EP',
    genre: 'Rock',
    release: '2015-05-19',
    price: '13000',
    download: '6010',
    listen: '3020',
  },
  {
    key: 18,
    name: "I'm Not The Only One",
    artist: 'Sam Smith',
    type: 'Single',
    genre: 'Pop,R&B',
    release: '',
    price: '',
    download: '',
    listen: '',
  },
];
